controller_list:
  - name: fake_delta_arm_1_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - uj_11
      - uj_12
      - uj_13
      - uj_14
  - name: fake_delta_arm_2_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_2
      - uj_21
      - uj_22
      - uj_23
      - uj_24
  - name: fake_delta_arm_3_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_3
      - uj_31
      - uj_32
      - uj_33
      - uj_34
  - name: fake_delta_irb360_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - uj_11
      - uj_12
      - uj_13
      - uj_14
      - joint_2
      - uj_21
      - uj_22
      - uj_23
      - uj_24
      - joint_3
      - uj_31
      - uj_32
      - uj_33
      - uj_34
initial:  # Define initial robot poses per group
  - group: delta_arm_1
    pose: arm_1_default
  - group: delta_arm_2
    pose: arm_2_default
  - group: delta_arm_3
    pose: arm_3_default