delta_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - uj_11
    - uj_12
    - uj_13
    - joint_2
    - uj_21
    - uj_22
    - uj_23
    - joint_3
    - uj_31
    - uj_32
    - uj_33
  gains:
    joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_21:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_22:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_23:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_31:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_32:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    uj_33:
      p: 100
      d: 1
      i: 1
      i_clamp: 1